// ignore_for_file: constant_identifier_names

const COLOR_PRIMARY = 0xFFFFFFFF;
const COLOR_PRIMARY_LIGHT = 0xFFFFFFFF;
const COLOR_PRIMARY_DARK = 0xFFFFFFFF;

const COLOR_SECONDARY = 0xFFD74745;
const COLOR_SECONDARY_LIGHT = 0xFFFF7970;
const COLOR_SECONDARY_DARK = 0xFF9F061D;

const COLOR_GRAD_BEG = 0xFFE35C32;
const COLOR_GRAD_END = 0xFFD74745;
